name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: '6.tcp.ngrok.io'
        username: 'zjulss'
        password: 'zjulss123456'
        port: '12443'
        script: |
          cd /home/zjulss/work/DGM-B
          go run server.go&
          cd /home/zjulss/work/DGM-B/livego
          go run live.go&
